### PR TITLE
Increases Axios file transfer limit

### LINKED ISSUE #23: Axios 10MB file transfer limit
## Expected Behavior
Ability to add reasonably large files.
Easily understood error message with appropriate context.

## Current Behavior
By default, Axios has a 10MB content limit.  Exceeding that limit throws an error stating:

> Request body larger than maxBodyLength limit

Along with some rather large and intimidating config and request objects.

## Possible Solution
I'm not sure what a "reasonable" limit is, but perhaps 100MB would be fair.

## Steps to Reproduce (for bugs)
Use `add` method to pin a file larger than 10MB.

## Context
I wanted to pin my nephews stop-motion video so he could share it with friends and family 🤗

## Your Environment
Node 12

### PR DESCRIPTION
**Pull request by MCTaylor17**
Resolves #23 

This PR Includes:
* Increased file transfer limit to 100MB
* Custom error including:
  - Relevant message
  - file size in bytes
  - maximum file size in bytes
  - detailed human readable explanation of the problem and possible solutions

Pending:
* Agreement on new file transfer limit
* Refactor to handle conditional logic within the FissionErrors file.

Future Considerations:
* User specific transfer limits

### CODE REVIEW

File: src/FissionErrors.ts [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+        maxContentLength: ByteLength
+    }
+}
+
+export class FileSizeError extends Error {
+  fileSizeBytes: ByteLength
+  maxFileSizeBytes: ByteLength
+  details: string
+  private axiosError: AxiosError
+  private AXIOS_DEFAULT_MAXIMUM = 10_000_000;
```
Comment (bechurch) [inline src/FissionErrors.ts]: This and all the other values that reference `10_000_000` bytes should be moved to the `constants.ts` file

File: src/FissionErrors.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
+export type ByteLength = number
```
Comment (bechurch) [inline src/FissionErrors.ts]: Lets rename this `errors.ts`

File: src/FissionErrors.ts [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+
+export interface AxiosError extends Error {
+    isAxiosError: boolean
```
Comment (bechurch) [inline src/FissionErrors.ts]: Given that this interface is `AxiosError` should it always be an axios error? We may not want to keep this field

File: src/FissionErrors.ts [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+    return (bytes / 1_000_000).toFixed(1) + "MB";
+  }
+
+  private constructDetails = (): string => {
+    const fileSize = this.humanReadable(this.fileSizeBytes);
+    const maxSize = this.humanReadable(this.maxFileSizeBytes);
+    const overage = this.humanReadable(this.fileSizeBytes - this.maxFileSizeBytes);
+    
+    return `---
+Oh no, the file you tried to add is too big 😲
```
Comment (bechurch) [inline src/FissionErrors.ts]: nice error message

File: src/client.ts [hunk 5]
```diff
@@ -33,12 +36,25 @@ export const add = async (
...
     auth
-  })
-  return data
+  }
+  
+  try {
+    const { data } = await axios.post<CID>(`${baseURL}/ipfs${nameStr}`, content, axiosOptions)
+    return data
+  } catch (err) {
+    switch (err.message) {
```
Comment (bechurch) [inline src/client.ts]: We shouldn't switch on the error message itself. It's both brittle and subtle. i.e. Axios could change this message and it wouldn't warrant a major or even minor version increase. This means that we could apply the latest patch containing the change and this branch of our logic would never be hit again.

File: src/FissionErrors.ts [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+    let maxFileSizeBytes = this.axiosError.config.maxContentLength;
+    
+    if(maxFileSizeBytes === -1) {
+      maxFileSizeBytes = this.AXIOS_DEFAULT_MAXIMUM;
+    }
+    
+    return maxFileSizeBytes;
+  }
+  
+  private humanReadable = (bytes: number): string => {
```
Comment (bechurch) [inline src/FissionErrors.ts]: We should limit class methods as much as possible.

We should:
1. Move the division to a named utility function in the `utils.ts` file
2. leave the `MB` in the error message

```js
// util.js
const byteToMBSize = (bytes) => (bytes / 1_000_000).toFixed(1)
```

```js
    
    return `---
Oh no, the file you tried to add is too big 😲
You tried sending ${fileSize} MB but your current max is ${maxSize}.
That means your file was ${overage} MB too big 😟
To solve this, you may want to try:
 * Compressing your file
 * Breaking the file into smaller files
 * Contacting the nice people at Fission for assistance
Warm Regards and sorry for the inconvenience,
The Fission Devs 🤗
---

**Comment by MCTaylor17** [comment]
Hey @bechurch,

Thanks for the solid review and feedback.  I started working on this aware you were refactoring things so I'm not surprised (the new changes look clean BTW).  Also, your comments are spot on.  Here's where I was taking things before hitting a wall with TypeScript (pseudo-code):

```ts
// src/api/ipfs.tx
try {
  // axios request
} catch (err) {
  throw axiosErrorHandler(err);
}

```ts
// src/errors.ts
const axiosErrorHandler = (axiosError: AxiosError): FissionError {
  switch(true) {
    case axiosError instanceof AxiosFileError
      return new FissionFileError(axiosError as AxiosFileError) as FissionError
    default:
       return err as FissionError
  }
} 
```
Unfortunately, I'm such a noob I didn't know I could just up-cast the types 🤦‍♂️

Anyways, more than anything I wanted to start a conversation about file-size limits.  Injecting UX into error messages is definitely more of a nice to have.  Setting size limits on the client-side and catching errors is probably the wrong approach altogether.  For example, it might be better to ask the server how much the `maxContentLength` should be and thow an error before the POST request is even made...

**Comment by MCTaylor17** [comment]
I don't think there was a clean way to rebase the changes so I backed-up [the original](https://github.com/MCTaylor17/typescript-client/tree/old-max-content-length) and force-pushed over this one.

I've updated this with the minimal changes required to increase the file-size limit to 100MB.  I manually tested it with a 60MB file and works great 👍

File: src/FissionErrors.ts (hunk 4 above)
Comment (MCTaylor17) [reply src/FissionErrors.ts]: Thank you 😄

File: src/FissionErrors.ts (hunk 6 above)
Comment (MCTaylor17) [reply src/FissionErrors.ts]: Since `toFixed()` returns a string, I'm tempted to do something like this:
```js
const bytesToMegabytesConversion = (bytes: number): number => (bytes / 1_000_000)
const magebytesToGigabytes = (megabytes: number): number => (megabytes / 1_000)

const humanReadableDataSize = (bytes: number, decimals: number): string => {
    let units = "MB"
    let value: number = bytesToMegabytesConversion(bytes)
    if(value > 1_000) {
        units = "GB"
        value = magebytesToGigabytes(value)
    }
    return value.toFixed(decimals) + units
}
```

File: src/client.ts (hunk 5 above)
Comment (MCTaylor17) [reply src/client.ts]: Okay, so I looked into this one and it turns out to be a little challenging.  Here's the problem:
```js
Object.getOwnPropertyNames(axiosError)
// [ 'stack', 'message', 'config', 'request', 'response', 'isAxiosError', 'toJSON' ]
```
Looking through the props, I can't see any other way to distinguish between errors other than message.  

What we could do is add the following to the test suite:
```js
describe("Axios Errors", () => {
  it("returns specific error message when maxContentLength exceeded", async () => {
    const axiosOptions = {
      headers: {
        'content-type': 'application/octet-stream'
      },
      maxContentLength: 1,
      auth: TEST_AUTH
    }
    expect.assertions(1)
    try {
      const { data } = await axios.post(`${BASE_URL_DEFAULT}/ipfs`, JSON_CONTENT, axiosOptions)
    } catch (axiosError) {
      expect(axiosError.message).toBe("Request body larger than maxBodyLength limit")
    }
  })
})
```
There could be some delay between releases where the problem goes unoticed, but if the fall back is to `throw axiosError`, it's exactly the same as not handling it.

There's also a problem using `instanceof` because it can only be checked against constructors (`class` or `interface`).  Unless there's a way around checking against the message, we end up with this: 
```js
export interface AxiosFileSizeError extends Error {
    config: {
        headers: {
            "Content-Length": ByteLength
        }
        maxContentLength: ByteLength
    }
}

export class AxiosFileSizeError extends Error {
    message: string = "Request body larger than maxBodyLength limit"
}
```

**Comment by MCTaylor17** [comment]
Hmmm... there might be a super simple way to avoid all of this error handling complexity:

```js
  if(JSON.stringify(content).length > maxContentLength) {
    throw new Error("File Size Error");
  }
```

I'm not sure what kind of performance hit this type of check would create though...

**Comment by dholms** [comment]
Hey @MCTaylor17, thanks for putting this PR up. I was cleaning up some stuff on GH and saw that it was never merged. The proposed code looks good to me :ok_hand: 

Is it good to go in your book? If so can you create the PR (instead of just a draft)?

It seems like the only outstanding question is about something like:
```
 if(JSON.stringify(content).length > maxContentLength) {
    throw new Error("File Size Error");
  }
```
The POST method works for JSON, strings, and file streams. This check would work well for JSON and strings, but not for file streams (which any 100MB requests will probably be file streams). To do a check on a file stream we would have to do one of the following:
- stream up to 100MB of the file into memory, before then sending it to axios
- open & stream the file twice, once to a file size checker, and then to axios
- split the stream to both axios & a file size checker

I don't like the memory hit of the first one, the second seems a bit roundabout, and I don't see the third being much of an improvement on just leaving the error handling to axios.

Let me know if I'm overlooking something/you have another perspective on this. Otherwise I say we leave the content size error handling to axios :+1:

**Comment by MCTaylor17** [comment]
@dholms sorry for the delay on this.

I made the mistake of combining two problems into one.  Fancy error handling isn't necessary to increase the file-size limit which was the issue I was facing.   

My feelings tend to align with your own.  At the time, I was worried about the performance hit of using JSON.stringify, so the idea of streaming data into memory is even more cringe.

As you say, leaving it to axios is probably the best bet.
